LIB = smarttools

INCLUDES = -I $(includedir)/newbase
CFLAGS = -DUNIX $(INCLUDES) -ansi -w2 -Werror -wd981,383,869,444,810,593

CC = /usr/local/intel/compiler70/ia32/bin/icc

# Common library compiling template

include ../../makefiles/makefile.lib

