get_filename_component(INSTALL_PREFIX ${SmartTools_DIR} DIRECTORY)
get_filename_component(INSTALL_PREFIX ${INSTALL_PREFIX} DIRECTORY)
get_filename_component(INSTALL_PREFIX ${INSTALL_PREFIX} DIRECTORY)
set(SmartTools_INCLUDE_DIRS ${INSTALL_PREFIX}/include)
set(SmartTools_INSTALLED_INCLUDE_DIRS ${INSTALL_PREFIX}/include/smarttools)
if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set(SmartTools_INSTALLED_LIBRARIES ${INSTALL_PREFIX}/lib/libSmartTools.a)
    set(SmartTools_LIBRARIES  ${INSTALLED_PREFIX}/lib/libSmartTools.a)
else()
    set(SmartTools_INSTALLED_LIBRARIES ${INSTALL_PREFIX}/lib/SmartTools.lib)
    set(SmartTools_LIBRARIES ${INSTALL_PREFIX}/lib/SmartTools.lib)
endif()
