get_filename_component(INSTALL_PREFIX ${SmartTools_DIR} DIRECTORY)
get_filename_component(INSTALL_PREFIX ${INSTALL_PREFIX} DIRECTORY)
get_filename_component(INSTALL_PREFIX ${INSTALL_PREFIX} DIRECTORY)
set(SmartTools_INCLUDE_DIRS ${INSTALL_PREFIX}/include)
set(SmartTools_INSTALLED_INCLUDE_DIRS ${INSTALL_PREFIX}/include/smarttools)
if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    # If static and shared library is available, one can select
    # which one to use. By default use shared one.
    option(SmartTools_USE_STATIC_LIBS "SmartTools use static libs" OFF)

    if(SmartTools_USE_STATIC_LIBS)
        find_library (SmartTools_STATIC_LIB "${CMAKE_STATIC_LIBRARY_PREFIX}SmartTools${CMAKE_STATIC_LIBRARY_SUFFIX}" ${INSTALLED_PREFIX})
        set(SmartTools_LIBRARIES  ${SmartTools_STATIC_LIB})
    else()
        find_library (SmartTools_SHARED_LIB "${CMAKE_SHARED_LIBRARY_PREFIX}SmartTools${CMAKE_SHARED_LIBRARY_SUFFIX}" ${INSTALLED_PREFIX})
        set(SmartTools_LIBRARIES  ${SmartTools_SHARED_LIB})
    endif()
else()
    option(SmartTools_USE_STATIC_LIBS "SmartTools use static libs" ON)

    if(SmartTools_USE_STATIC_LIBS)
        find_library (SmartTools_STATIC_LIB "${CMAKE_STATIC_LIBRARY_PREFIX}SmartTools${CMAKE_STATIC_LIBRARY_SUFFIX}" ${INSTALLED_PREFIX})
        set(SmartTools_LIBRARIES  ${SmartTools_STATIC_LIB})
    else()
        find_library (SmartTools_SHARED_LIB "${CMAKE_SHARED_LIBRARY_PREFIX}SmartTools${CMAKE_SHARED_LIBRARY_SUFFIX}" ${INSTALLED_PREFIX})
        set(SmartTools_LIBRARIES  ${SmartTools_SHARED_LIB})
    endif()
endif()
